import cv2

image = cv2.imread('test.jpeg')
cv2.imshow("mine", image)
cv2.waitKey(0)
grey_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("New Dog", grey_img)
cv2.waitKey(0)
inverted_img = cv2.bitwise_not(grey_img)
cv2.imshow("Inverted", inverted_img)
cv2.waitKey()
blur_img = cv2.GaussianBlur(inverted_img, (21,21), 00)
inverted_blur_img = cv2.bitwise_not(blur_img)
sketch = cv2.divide(grey_img, inverted_blur_img, scale=256.0)
cv2.imwrite('sketch.png', sketch)
cv2.imshow("Sketch", sketch)
cv2.imshow("original image", image)
cv2.imshow("pencil sketch", sketch)
cv2.waitKey(0)
cv2.waitKey(0)
